### ISSUE TITLE
Hackland election compilation error 

### ISSUE THREAD

**Issue by dhiru1501** [spdeepak/hackerrank#1]
Solution.java:21: error: cannot find symbol
                System.out.println(Collections.max(map.entrySet(),Map.Entry.comparingByValue()).getKey());   
                                                                           ^
  symbol:   method comparingByValue()
  location: interface Entry
1 error
At Compilation time I got an error

**Comment by spdeepak** [comment]
Which version of Java are you using?

**Comment by dhiru1501** [comment]
Java7 version

**Comment by spdeepak** [comment]
If you see the [pom file](https://github.com/spdeepak/hackerrank/blob/master/pom.xml) it clearly says Java 8 as the version.

**Comment by spdeepak** [comment]
Closing the ticket due to no response.

**Comment by dhiru1501** [comment]
Thanks buddy
